### ISSUE TITLE
Is "settings.txt" mean't to be "settingtypes.txt"?

### ISSUE THREAD

**Issue by Panquesito7** [MinetestForFun/fishing#3]

**Comment by BetterToAutomateTheWorld** [comment]
Good question, I can't tell and unfortunately crabman77 is missing since a long time now

**Comment by Panquesito7** [comment]
You can create a pull request and try to fix it.

**Comment by ObaniGemini** [comment]
We won't.

**Comment by Panquesito7** [comment]
Should I close the issue, then?

**Comment by BetterToAutomateTheWorld** [comment]
Better to close this issue I guess, thank you anyway @Panquesito7 for your work :)
